# Generated by Django 5.2.6 on 2025-09-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('meal_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
