# Generated by Django 5.2.6 on 2025-09-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Mic dejun'), ('lunch', 'Prânz'), ('dinner', 'Cină'), ('snack', 'Snack')], default='lunch', max_length=20),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_name',
            field=models.CharField(max_length=100),
        ),
    ]
