# Generated by Django 5.2.6 on 2025-09-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_remove_meal_user_id_alter_meal_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('snack', 'snack')], default='lunch', max_length=20),
        ),
    ]
